### ISSUE TITLE
Application crashes immediately after being built.

### ISSUE THREAD

**Issue by peteygao** [hariroshan/ex2-weather#1]
System info:
```
macOS 12.7.2
Xcode 14.2 Build version 14C18
NativeScript version 8.8.1
```

I've gotten NativeScript setup properly and the build works, however when I run `npm run run:ios`, I get this error after the simulator boots up:
```
Project successfully built.
Build time: 16.076 s.
The build result is located at: /Users/pyg/Development/elm-nativescript/platforms/ios/build/Debug-iphonesimulator/elmnativescript.app
Installing on device 17B86670-9ABC-4CAF-8F8A-8B808AE87D19...
Successfully installed on device with identifier '17B86670-9ABC-4CAF-8F8A-8B808AE87D19'.
Successfully transferred bundle.js on device 17B86670-9ABC-4CAF-8F8A-8B808AE87D19.
Successfully transferred package.json on device 17B86670-9ABC-4CAF-8F8A-8B808AE87D19.
Successfully transferred runtime.js on device 17B86670-9ABC-4CAF-8F8A-8B808AE87D19.
Successfully transferred tns_modules on device 17B86670-9ABC-4CAF-8F8A-8B808AE87D19.
Successfully transferred inspector_modules.js on device 17B86670-9ABC-4CAF-8F8A-8B808AE87D19.
Successfully transferred vendor.js on device 17B86670-9ABC-4CAF-8F8A-8B808AE87D19.
Restarting application on device 17B86670-9ABC-4CAF-8F8A-8B808AE87D19...
  ***** Fatal JavaScript exception - application has been terminated. *****
  NativeScript encountered a fatal error:
  Error calling module function
  Error calling module function
  ReferenceError: __APPLE__ is not defined
  File: (file: app/webpack:/blank/webpack/bootstrap:27:0)
  StackTrace:
  	./node_modules/@nativescript/core/accessibility/font-scale-common.js(file: app/webpack:/blank/node_modules/@nativescript/core/accessibility/font-scale-common.js:1:7)
  	at __webpack_require__(file: app/webpack:/blank/webpack/bootstrap:24:0)
  	at fn(file: app/webpack:/blank/webpack/runtime/hot module replacement:62:0)
  	at ./node_modules/@nativescript/core/accessibility/accessibility-css-helper.js(file:///app/vendor.js:95:69)
  	at __webpack_require__(file: app/webpack:/blank/webpack/bootstrap:24:0)
  	at fn(file: app/webpack:/blank/webpack/runtime/hot module replacement:62:0)
  	at ./node_modules/@nativescript/core/application/application-common.js(file:///app/vendor.js:1227:97)
  	at __webpack_require__(file: app/webpack:/blank/webpack/bootstrap:24:0)
  	at fn(file: app/webpack:/blank/webpack/runtime/hot module replacement:62:0)
  	at ./node_modules/@nativescript/core/application/application.ios.js(file:///app/vendor.js:2126:77)
  	at __webpack_require__(file: app/webpack:/blank/webpack/bootstrap:24:0)
  	at fn(file: app/webpack:/blank/webpack/runtime/hot module replacement:62:0)
  	at ./node_modules/@nativescript/core/appl<…>
```

So, this seems to be something to do with either how Webpack is bootstrapping the application, or the NativeScript configuration. Any idea how to debug this?

**Comment by hariroshan** [comment]
Has been addressed here. Now minimum supported iOS version is 13.0

https://github.com/hariroshan/template-blank-elm/pull/1

Thanks @peteygao.
